name: Build for Windows

on:
  push:
    branches:
      master
  workflow_dispatch:  # Manual trigger

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-portaudio
          mingw-w64-x86_64-ncurses
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-jsoncpp

    - name: Set up MSYS2 environment
      run: |
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
        echo "C:/msys64/usr/bin" >> $GITHUB_PATH
        
    - name: Compile the application
      run: |
        make -f Makefile

    - name: Bundle agbplay.json with the executable
      run: |
        cp agbplay.json ./bin/

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: agbplay-windows-build
        path: ./bin/*
